# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.1
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=wazuh.manager
    networks: [wazuh]
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
networks:
  wazuh:
    external: true
    name: wazuh-network
