include:
  - nosql-query-me/docker-compose.yml
services:
  ping-service:
    build: ping-service
    networks:
      - wazuh
    ports:
      - "13300:5000"
  never-trust-the-client:
    build: never-trust-the-client
    ports:
      - "13301:5000"
  query-me:
    build: query-me
    ports:
      - "13302:5000"
  not-an-admin:
    build: not-an-admin
    ports:
      - "13304:5000"
  my-jwt:
    build: my-jwt
    ports:
      - "13305:8000"
networks:
  wazuh:
    name: wazuh-network
    external: true
